apps = [
    {
        "app_name": "Weather",
        "app_function": [
            "View current weather forecasts for the current city and surrounding areas",
            "Provide weather forecasts for the next few hours and days",
            "Display weather indicators such as temperature, humidity, wind speed, and direction",
            "Provide life indices such as air quality, clothing suggestions, etc.",
            "Support weather inquiries for multiple cities",
            "Can set cities of interest for easy viewing of weather conditions in different areas",
        ],
        "launch_command": "com.huawei.android.totemweather/.WeatherMainActivity",
    },
    {
        "app_name": "baidu map",
        "app_function": [
            "Find places and routes: Search for specific places, view maps, and get route guidance.",
            "Real-time navigation: Provide real-time navigation guidance to help users reach their destination.",
            "Surrounding service information: Display information about nearby shops, restaurants, hospitals, etc.",
            "Public transportation information: Provide information on public transportation routes, schedules, and fares.",
            "Bookmark and mark locations: Users can bookmark frequently visited places and mark important locations on the map.",
            "Real-time traffic conditions: Display real-time traffic conditions to help users choose the best route.",
            "Voice navigation: Support voice navigation to facilitate user operation during driving.",
        ],
        "launch_command": "com.baidu.maps.caring/com.baidu.baidumaps.MapsActivity",
    },
    {
        "app_name": "calculator",
        "app_function": [
            "Basic arithmetic operations: Addition, subtraction, multiplication, and division.",
            "Scientific functions: Trigonometric functions, logarithms, square roots, etc.",
            "Memory functions: Store and recall numbers for calculations.",
            "Percentage calculations: Calculate percentages of numbers.",
            "History tracking: View and recall previous calculations.",
            "Customization options: Adjust settings for precision, display format, etc.",
            "Unit conversions: Convert between different units of measurement.",
        ],
        "launch_command": "com.huawei.calculator/.Calculator",
    },
    {
        "app_name": "Didi",
        "app_function": [
            "Scheduled rides: Can schedule travel time and location in advance, convenient for the elderly to arrange trips.",
            "Instant rides: Support calling nearby available vehicles anytime, anywhere, to meet immediate travel needs.",
            "View vehicle location: View the real-time location and distance of nearby vehicles on the map.",
            "Choose vehicle type: Can choose different types of vehicles according to needs, such as Comfort, Luxury, etc.",
            "Payment methods: Support multiple payment methods, including online payment and cash payment.",
            "Driver rating: After the ride, passengers can rate the driver to help improve service quality.",
            "Safety features: Provide emergency contact and trip sharing features to increase travel safety.",
        ],
        "launch_command": "com.sdu.didi.psnger/com.didi.sdk.app.launch.splash.SplashActivity",
    },
    {
        "app_name": "Feizhu",
        "app_function": [
            "Search, compare, and book transportation such as flights, train tickets, bus tickets, etc.",
            "Browse and book accommodation services such as hotels, homestays, etc.",
            "View tourist attractions information and book tickets",
            "Plan and manage travel plans, including itinerary arrangements and budget management",
            "Get real-time travel reminders and itinerary change notifications",
            "Pay reservation fees online",
        ],
        "launch_command": "com.taobao.trip/.home.HomeActivity",
    },
    {
        "app_name": "Alipay",
        "app_function": [
            "Mobile payment: Support online payment, transfer, and payment of utilities, credit card bills, etc.",
            "Financial management: Provide wealth management, insurance, and other financial services.",
            "Life services: Can pay for water and electricity bills, phone bills, and other daily expenses.",
            "Discounts and coupons: Provide various discounts and coupons for shopping and dining.",
            "Scan code payment: Support scanning code payment in physical stores and online shopping.",
            "Fund transfer: Can transfer money to friends and family through the app.",
            "Investment services: Provide investment and financial planning services.",
        ],
        "launch_command": "com.eg.android.AlipayGphone/.AlipayLogin",
    },
    {
        "app_name": "camera",
        "app_function": [
            "Take photos: Capture photos by clicking the capture button",
            "Record videos: Record video clips, long-press the capture button to start recording",
            "View photos and videos: View captured photos and videos in the gallery",
            "Edit photos: Provide basic photo editing functions such as cropping, rotating, applying filters, etc.",
            "Share photos and videos: Share captured content via social media, messaging apps, etc.",
            "Settings: Adjust camera parameters such as flash, gridlines, etc.",
        ],
        "launch_command": "com.huawei.camera/com.huawei.camera",
    },
    {
        "app_name": "calendar",
        "app_function": [
            "Schedule management: Create, edit, and delete events, appointments, and reminders.",
            "Event notifications: Receive reminders and notifications for upcoming events and tasks.",
            "Multiple calendar views: Switch between daily, weekly, monthly, and yearly views for better planning.",
            "Sync with other devices: Synchronize calendar data with other devices for easy access and backup.",
            "Customizable settings: Adjust settings for event colors, notifications, time zones, etc.",
            "Holiday calendars: Display national holidays and festivals for reference.",
            "Task lists: Create to-do lists and manage tasks within the calendar app.",
        ],
        "launch_command": "com.android.calendar/.AllInOneActivity",
    },
    {
        "app_name": "duolingo",
        "app_function": [
            "Language learning: Provide courses in various languages to help users learn new languages.",
            "Listening exercises: Practice listening skills by listening to spoken sentences and selecting the correct translation.",
            "Speaking exercises: Practice speaking skills by repeating sentences and comparing pronunciation.",
            "Writing exercises: Practice writing skills by typing translations of sentences.",
            "Vocabulary exercises: Learn new words and phrases through vocabulary exercises.",
            "Progress tracking: Track learning progress and receive feedback on performance.",
            "Daily goals: Set daily learning goals to stay motivated and consistent.",
        ],
        "launch_command": "com.duolingo/.app.LoginActivity",
    },
    {
        "app_name": "cainiao",
        "app_function": [
            "Parcel tracking: Track the status and location of parcels in real-time.",
            "Delivery services: Schedule package pickup and delivery services.",
            "Address book: Manage sender and recipient addresses for easy order placement.",
            "Payment options: Support various payment methods for shipping fees and services.",
            "Customer service: Access customer support for inquiries, complaints, and feedback.",
            "Notifications: Receive notifications on package status updates and delivery schedules.",
            "User account: Create and manage user accounts for personalized services.",
        ],
        "launch_command": "com.cainiao.wireless/.homepage.view.activity.HomePageActivity",
    },
    {
        "app_name": "taobao",
        "app_function": [
            "Online shopping: Browse, search, and purchase products from various categories.",
            "Discounts and promotions: Receive discounts, coupons, and promotions for shopping.",
            "Order tracking: Track the status of orders, view order history, and manage returns.",
            "Store browsing: Explore different online stores, view product details, and read reviews.",
            "Payment options: Support various payment methods, including Alipay, credit cards, etc.",
            "Customer service: Contact customer service for inquiries, complaints, and feedback.",
            "Product recommendations: Receive personalized product recommendations based on browsing history.",
        ],
        "launch_command": "com.taobao.taobao/com.taobao.tao.welcome.Welcome",
    },
    {
        "app_name": "WeChat",
        "app_function": [
            "Messaging: Send and receive text messages, voice messages, photos, and videos.",
            "Voice and video calls: Make voice and video calls to contacts.",
            "Moments: Share updates, photos, and videos with friends in the Moments feed.",
            "Mini programs: Access mini programs for various services and functions.",
            "Payment: Send and receive money, pay bills, and make purchases within the app.",
            "Group chats: Create and participate in group chats with multiple contacts.",
            "Official accounts: Follow official accounts for news, updates, and services.",
        ],
        "launch_command": "com.tencent.mm/com.tencent.mm.ui.LauncherUI",
    },
    {
        "app_name": "douyin",
        "app_function": [
            "Short videos: Watch and share short videos created by users.",
            "Live streaming: Watch live broadcasts and interact with streamers and other viewers.",
            "Trending challenges: Participate in trending challenges and create your own videos.",
            "Follow creators: Follow your favorite creators to stay updated on their content.",
            "Personalized feed: Receive recommendations based on your interests and viewing history.",
            "Comments and likes: Like, comment, and share videos with other users.",
            "Privacy settings: Adjust privacy settings for account visibility and data protection.",
        ],
        "launch_command": "com.ss.android.ugc.aweme/.splash.SplashActivity",
    },
    {
        "app_name": "tencent video",
        "app_function": [
            "Video streaming: Watch movies, TV shows, and videos on demand.",
            "Offline downloads: Download videos for offline viewing.",
            "Recommendations: Receive personalized recommendations based on viewing history.",
            "Playback controls: Control video playback with options for pause, rewind, fast forward, etc.",
            "User account: Create and manage user accounts for personalized services.",
        ],
        "launch_command": "com.tencent.qqlive/.ona.activity.SplashHomeActivity",
    },
    {
        "app_name": "Message",
        "app_function": [
            "Send and receive text messages: Exchange text messages with contacts.",
            "Multimedia messaging: Send and receive photos, videos, and audio messages.",
            "Group messaging: Create and participate in group chats with multiple contacts.",
            "Message notifications: Receive notifications for new messages and updates.",
            "Message search: Search for specific messages or content within messages.",
            "Message settings: Customize message settings such as notifications, sounds, etc.",
        ],
        "launch_command": "com.android.mms/.ui.ConversationList",
    },
    {
        "app_name": "MeiPian",
        "app_function": [
            "Create articles: Write and publish articles with text, photos, and videos.",
            "Templates and themes: Choose from various templates and themes for article design.",
            "Social sharing: Share articles on social media platforms and messaging apps.",
            "Community interaction: Engage with other users through comments, likes, and follows.",
            "Analytics: Track article performance with analytics on views, likes, and shares.",
            "Monetization: Earn money through sponsored content and advertising.",
            "Profile customization: Customize user profiles with bios, photos, and links.",
        ],
        "launch_command": "com.lanjingren.ivwen/.ui.MainTabActivity",
        # 权限问题无法打开
    },
    {
        "app_name": "HongSong",
        "app_function": [
            "Senior University Courses: Offering classes in singing, musical instruments, recitation, calligraphy, painting, dance, traditional Chinese medicine, opera, photography, and more.",
            "Senior Interest-Based Socializing: Engage in live interactions, offline gatherings, and join different classes for learning and socializing.",
            "Live Teaching by Renowned Instructors: Renowned instructors and university lecturers conduct live teaching sessions, provide guidance to students, and offer class group discussions and homework reviews.",
        ],
        "launch_command": "com.hongsong.live.lite/com.hongsong.fengjing.fjfun.home.FJMainActivity",
        # 权限问题无法打开
    },
    {
        "app_name": "MeiPai",
        "app_function": [
            "Short video creation: Record and edit short videos with various effects and filters.",
            "Live streaming: Broadcast live videos to interact with viewers in real-time.",
            "Video editing: Edit videos with features like trimming, merging, adding music, etc.",
            "Beauty filters: Apply beauty filters and effects to enhance video quality.",
            "Social sharing: Share videos on social media platforms and messaging apps.",
            "Trending challenges: Participate in trending challenges and contests.",
            "Monetization: Earn money through sponsored content and advertising.",
        ],
        "launch_command": "com.meitu.meipaimv/.community.main.MainActivity",
    },
    {
        "app_name": "Doubao",
        "app_function": [
            "Conversation: Have engaging conversations on various topics.",
            "Answer questions: Provide accurate and detailed answers.",
            "Suggestion offering: Give tailored suggestions based on user input.",
            "Emotional support: Offer comfort and understanding in times of need.",
            "Knowledge coverage: Cover a wide range of subjects and fields.",
        ],
        "launch_command": "com.larus.nova/com.larus.bmhome.MainActivity",
    },
    {
        "app_name": "Clock",
        "app_function": [
            "Set alarms: Create and manage alarms for waking up, reminders, etc.",
            "World clock: View time zones and current times for different cities.",
            "Timer: Set countdown timers for various activities.",
            "Stopwatch: Use a stopwatch for timing activities and events.",
            "Customizable clock faces: Choose from different clock faces and themes.",
            "Bedtime mode: Set bedtime schedules and receive reminders for better sleep habits.",
        ],
        "launch_command": "com.android.deskclock/.AlarmsMainActivity",
        
    },
    {
        "app_name": "app store",
        "app_function": [
            "App search and download: Search for apps and download them to the device.",
            "App updates: Receive notifications for app updates and install them.",
            "App recommendations: Get personalized app recommendations based on usage patterns.",
            "App management: Manage installed apps, including updates, permissions, and storage.",
            "App categories: Browse apps by categories such as games, social, productivity, etc.",
            "App permissions: Review and manage app permissions for privacy and security.",
        ],
        "launch_command": "com.huawei.appmarket/.MarketActivity",
    }
]
