loca_or_collo_exp = [
    "帮我照一下亮",
    "我买三斤大米，一斤大米8块8，一共多少钱",
    "哪趟头的地铁去闸北公园呢",
    "帮我叫个车",
    "看看附近有么有公园",
    "帮我看看哪里可以喝面条",
    "看看今天的天儿咋样",
    "我要照个相儿",
    "帮我算个帐",
    "咱这附近有啥好吃的",
    "我想翻这个月的日历看看",
    "帮我导个航去五角场",
    "给我查查火车票",
    "这附近有没有哪里可以逛逛街，买点东西",
    "我想学会儿英语",
    "帮我看看明天的天儿好不好出门",
    "需要寄个快递，帮我约一下",
    "想买个特产",
    "把李阿姨的号儿存到手机里，号码是123456",
    "帮我打开手机里面的向导",
    "打开支付宝，看水电煤",
]
refined_loca_or_collo_exp = [
    "打开手电筒功能。",
    "请计算三斤大米的总价，每斤大米价格为8元8角。",
    "请打开地铁路线查询，查看去往闸北公园的地铁线路。",
    "打开打车软件，为我预约一辆出租车。",
    "打开地图应用，搜索附近的公园。",
    "打开附近餐馆搜索功能，查找可以吃面条的地方。",
    "打开天气预报应用，查看今天的天气情况。",
    "打开相机应用，准备拍照。",
    "打开计算器应用，进行账目计算。",
    "附近有什么美食推荐？",
    "请打开日历应用，查看本月的日历安排。",
    "打开地图应用，设定目的地为五角场，并开始导航。",
    "打开火车票查询应用。",
    "请打开地图应用，搜索附近的商业街或购物中心。",
    "打开英语学习应用程序。",
    "打开天气预报应用，查询明天的天气情况。",
    "请帮我预约快递服务。",
    "打开购物应用，搜索当地特产。",
    "将李阿姨的电话号码123456保存到手机联系人中。",
    "打开手机中的导航应用。",
    "打开支付宝应用，查询水电煤气费用。",
]
ambiguity_exp = [
    "设一个6点的闹钟",
    "周末提醒我去参加一场婚礼",
    "帮我打开交通码",
    "在市中心找一家星巴克",
    "下周提醒我去医院复查",
    "帮我定张下周去北京的票",
    "打开微信宝",
    "我最近去上海，帮我订个票",
    "那个，帮我看一下账户余额",
    "我要看看我爱我家",
    "帮我下载一个适合老同志的软件",
    "打开哈啰",
    "帮我导航去chongqing",
    "我想去朝阳",
    "看一下美拍",
    "看一下美篇",
    "帮我找找红松",
    "帮我看一下豆包",
]
ambiguity_questions = [
    ["您是想要设定早上6点的闹钟还是晚上6点的闹钟？"],
    ["您是想要在周六还是周日提醒您参加婚礼？", "婚礼是在上午还是下午举行？"],
    ["您是想打开地铁的交通码还是公交车的交通码？"],
    ["您是想找离您最近的星巴克吗？", "您是想找市中心评价最高的星巴克吗？"],
    ["您是想在下周的哪一天去医院复查？", "您需要在上午还是下午去医院复查？"],
    ["您是想订飞机票还是火车票？", "请问您具体想要哪一天出发去北京？"],
    ["您是想打开微信还是支付宝？"],
    ["您是想订机票还是火车票？", "您想订哪一天的票？"],
    ["您是想查看哪个账户的余额？是银行账户还是支付宝账户？"],
    ["您是想打开我爱我家的房地产应用程序还是观看我爱我家的电视剧？"],
    [
        "您是想下载一个适合老年人使用的软件吗，还是想下载一个适合同性恋者使用的软件？",
        "请问您具体想要哪一类的软件？比如健康管理，娱乐，还是社交？",
    ],
    ["您是想打开Hello语音助手还是某个名为Hello的应用程序？"],
    ["您是要去重庆的哪个地方呢？", "您是要开车去还是乘坐公共交通呢？"],
    ["您是想去北京市朝阳区还是辽宁省朝阳市？"],
    ["您是想要打开美拍应用程序还是查看拍摄的相关内容?"],
    ["您是想要浏览美篇的网页还是打开美篇的手机应用程序？"],
    ["您是想查看红松树的信息还是想打开红松app？"],
    ["您是想打开豆包应用程序还是查看有关豆包食品的信息？"],
]
ambiguity_answers = [
    ["早上6点"],
    ["周六", "上午"],
    ["地铁交通码"],
    ["不是", "是的"],
    ["周三", "上午"],
    ["飞机票", "下周二"],
    ["微信"],
    ["机票", "下周三"],
    ["支付宝"],
    ["看我爱我家的电视剧"],
    ["适合老年人的软件", "健康管理"],
    ["应用程序"],
    ["不是重庆，是崇庆", "开车"],
    ["北京朝阳区"],
    ["打开美拍程序"],
    ["打开美篇应用"],
    ["打开红松app"],
    ["打开豆包应用程序"],
]
integrated_exp = [
    "设定一个早上6点的闹钟。",
    "周六上午提醒我去参加婚礼。",
    "打开地铁的交通码。",
    "找市中心评价最高的星巴克。",
    "提醒我下周三上午去医院复查.",
    "订一张下周二去北京的飞机票。",
    "打开微信。",
    "订一张下周三去上海的机票。",
    "查看支付宝账户的余额.",
    "打开我爱我家电视剧观看.",
    "下载一个适合老年人的健康管理软件。",
    "打开名为Hello的应用程序。",
    "导航到崇庆，使用驾车模式。",
    "导航到北京市朝阳区。",
    "打开美拍应用程序.",
    "打开美篇手机应用程序。",
    "打开红松app。",
    "打开豆包应用程序.",
]
refined_cmd = [
    {
        "app_name": "Clock",
        "launch_command": "com.android.deskclock/.AlarmsMainActivity",
        "user_command": "设定一个早上6点的闹钟。",
    },
    {
        "app_name": "calendar",
        "launch_command": "com.android.calendar/.AllInOneActivity",
        "user_command": "周六上午提醒我去参加婚礼。",
    },
    {
        "app_name": "baidu map",
        "launch_command": "com.baidu.maps.caring/com.baidu.baidumaps.MapsActivity",
        "user_command": "打开地铁的交通码。",
    },
    {
        "app_name": "baidu map",
        "launch_command": "com.baidu.maps.caring/com.baidu.baidumaps.MapsActivity",
        "user_command": "找市中心评价最高的星巴克。",
    },
    {
        "app_name": "calendar",
        "launch_command": "com.android.calendar/.AllInOneActivity",
        "user_command": "提醒我下周三上午去医院复查",
    },
    {
        "app_name": "Feizhu",
        "launch_command": "com.taobao.trip/.home.HomeActivity",
        "user_command": "订一张下周二去北京的飞机票。",
    },
    {
        "app_name": "WeChat",
        "launch_command": "com.tencent.mm/com.tencent.mm.ui.LauncherUI",
        "user_command": "",
    },
    {
        "app_name": "Feizhu",
        "launch_command": "com.taobao.trip/.home.HomeActivity",
        "user_command": "订一张下周三去上海的机票",
    },
    {
        "app_name": "Alipay",
        "launch_command": "com.eg.android.AlipayGphone/.AlipayLogin",
        "user_command": "查看账户的余额",
    },
    {
        "app_name": "tencent video",
        "launch_command": "com.tencent.qqlive/.ona.activity.SplashHomeActivity",
        "user_command": "观看我爱我家电视剧",
    },
    {
        "app_name": "app store",
        "launch_command": "com.huawei.appmarket/.MarketActivity",
        "user_command": "下载适合老年人的健康管理软件。",
    },
    {"app_name": "Hello", "launch_command": "", "user_command": ""},
    {
        "app_name": "baidu map",
        "launch_command": "com.baidu.maps.caring/com.baidu.baidumaps.MapsActivity",
        "user_command": "导航到崇庆，使用驾车模式。",
    },
    {
        "app_name": "baidu map",
        "launch_command": "com.baidu.maps.caring/com.baidu.baidumaps.MapsActivity",
        "user_command": "导航到北京市朝阳区。",
    },
    {
        "app_name": "MeiPai",
        "launch_command": "com.meitu.meipaimv/.community.main.MainActivity",
        "user_command": "",
    },
    {
        "app_name": "MeiPian",
        "launch_command": "com.lanjingren.ivwen/.ui.MainTabActivity",
        "user_command": "",
    },
    {
        "app_name": "HongSong",
        "launch_command": "com.hongsong.live.lite/com.hongsong.fengjing.fjfun.home.FJMainActivity",
        "user_command": "",
    },
    {
        "app_name": "Doubao",
        "launch_command": "com.larus.nova/com.larus.bmhome.MainActivity",
        "user_command": "",
    },
]
unrefined_cmd = [
    {
        "app_name": "Clock",
        "launch_command": "com.android.deskclock/.AlarmsMainActivity",
        "user_command": "设 一个6点的闹钟",
    },
    {
        "app_name": "calendar",
        "launch_command": "com.android.calendar/.AllInOneActivity",
        "user_command": "周末提醒我去参加一场婚礼",
    },
    {
        "app_name": "Alipay",
        "launch_command": "com.eg.android.AlipayGphone/.AlipayLogin",
        "user_command": "",
    },
    {
        "app_name": "baidu map",
        "launch_command": "com.baidu.maps.caring/com.baidu.baidumaps.MapsActivity",
        "user_command": "在市中心找一家星巴克",
    },
    {
        "app_name": "calendar",
        "launch_command": "com.android.calendar/.AllInOneActivity",
        "user_command": "下周提醒我去医院复查",
    },
    {
        "app_name": "Feizhu",
        "launch_command": "com.taobao.trip/.home.HomeActivity",
        "user_command": "定张下周去北京的票",
    },
    {
        "app_name": "WeChat",
        "launch_command": "com.tencent.mm/com.tencent.mm.ui.LauncherUI",
        "user_command": "",
    },
    {
        "app_name": "Feizhu",
        "launch_command": "com.taobao.trip/.home.HomeActivity",
        "user_command": "帮我订个票",
    },
    {
        "app_name": "Alipay",
        "launch_command": "com.eg.android.AlipayGphone/.AlipayLogin",
        "user_command": "帮我看一下账户余额",
    },
    {
        "app_name": "MeiPian",
        "launch_command": "com.lanjingren.ivwen/.ui.MainTabActivity",
        "user_command": "我要看看我爱我家",
    },
    {
        "app_name": "HongSong",
        "launch_command": "com.hongsong.live.lite/com.hongsong.fengjing.fjfun.home.FJMainActivity",
        "user_command": "",
    },
    {
        "app_name": "Doubao",
        "launch_command": "com.larus.nova/com.larus.bmhome.MainActivity",
        "user_command": "",
    },
    {
        "app_name": "baidu map",
        "launch_command": "com.baidu.maps.caring/com.baidu.baidumaps.MapsActivity",
        "user_command": "导航去chongqing",
    },
    {
        "app_name": "baidu map",
        "launch_command": "com.baidu.maps.caring/com.baidu.baidumaps.MapsActivity",
        "user_command": "我想去朝阳",
    },
    {
        "app_name": "MeiPai",
        "launch_command": "com.meitu.meipaimv/.community.main.MainActivity",
        "user_command": "看一下美拍",
    },
    {
        "app_name": "MeiPian",
        "launch_command": "com.lanjingren.ivwen/.ui.MainTabActivity",
        "user_command": "看一下美篇",
    },
    {
        "app_name": "HongSong",
        "launch_command": "com.hongsong.live.lite/com.hongsong.fengjing.fjfun.home.FJMainActivity",
        "user_command": "找找红松",
    },
    {
        "app_name": "Doubao",
        "launch_command": "com.larus.nova/com.larus.bmhome.MainActivity",
        "user_command": "看一下豆包",
    },
]
origin_user_cmds = [
    "先查查微信余额，再转账给kc",
    "给小王发消息，还有小张",
    "请告诉我今天的天气，然后帮我订一张明天去上海的机票",
    "下周一下午三点提醒我去医院拿药，四点半去孙子学校接他放学",
    "设置个明天会议的提醒，然后微信发消息给kc",
    "明天要去闸北公园春游，帮我看看那边的路线和天气",
    "医生说我明早八点吃药，下午再去医院找他。记得提醒我",
    "叫kc明天出来玩，然后帮我看看天气适合穿什么衣服去见她",
]
choose_app = [
    {
        "app_name": "WeChat",
        "launch_command": "com.tencent.mm/com.tencent.mm.ui.LauncherUI",
        "user_command": "查查余额，再转账给kc",
    },
    {
        "app_name": "Message",
        "launch_command": "com.android.mms/.ui.ConversationList",
        "user_command": "给小王发消息，还有小张",
    },
    {
        "app_name": "Weather",
        "launch_command": "com.huawei.android.totemweather/.WeatherMainActivity",
        "user_command": "请告诉我今天的天气",
    },
    {
        "app_name": "calendar",
        "launch_command": "com.android.calendar/.AllInOneActivity",
        "user_command": "下周一下午三点提醒我去医院拿药，四点半去孙子学校接他放学",
    },
    {
        "app_name": "calendar",
        "launch_command": "com.android.calendar/.AllInOneActivity",
        "user_command": "设置个明天会议的提醒",
    },
    {
        "app_name": "baidu map",
        "launch_command": "com.baidu.maps.caring/com.baidu.baidumaps.MapsActivity",
        "user_command": "帮我看看闸北公园的路线",
    },
    {
        "app_name": "Clock",
        "launch_command": "com.android.deskclock/.AlarmsMainActivity",
        "user_command": "明早八点吃药，下午去医院找医生。提醒我",
    },
    {
        "app_name": "Weather",
        "launch_command": "com.huawei.android.totemweather/.WeatherMainActivity",
        "user_command": "帮我看看天气适合穿什么衣服去见她",
    },
]
baseline_refined_user_cmds = [
    ["查查微信余额", "转账给kc"],
    ["给小王发消息", "给小张发消息"],
    ["查询今天的天气", "订购明天去上海的机票"],
    ["提醒我下周一下午三点去医院拿药", "提醒我下周一四点半去孙子学校接他放学"],
    ["设置明天会议的提醒", "微信发消息给kc"],
    ["查看明天闸北公园的路线", "查看明天闸北公园的天气"],
    ["设置明早八点吃药提醒", "设置下午去医院找医生提醒"],
    ["给kc发信息约她明天出来玩", "查看明天的天气预报", "根据天气建议穿什么衣服去见kc"],
]
cot_refined_user_cmds = [
    ["查查微信余额", "转账给kc"],
    ["给小王发消息", "给小张发消息"],
    ["告诉我今天的天气", "帮我订一张明天去上海的机票"],
    ["下周一下午三点提醒我去医院拿药", "下周一四点半去孙子学校接他放学"],
    ["设置明天会议的提醒", "微信发消息给kc"],
    ["查看明天闸北公园的路线", "查看明天闸北公园的天气"],
    ["明早八点吃药", "下午去医院找医生", "提醒我"],
    ["叫kc明天出来玩", "帮我看看天气适合穿什么衣服去见她"],
]
one_shot_refined_user_cmds = [
    ["查询微信余额", "给kc微信转账"],
    ["给小王发消息", "给小张发消息"],
    ["查询今天的天气", "订购明天去上海的机票"],
    ["下周一下午三点提醒我去医院拿药", "下周一下午四点半提醒我去孙子学校接他放学"],
    ["设置明天会议的提醒", "微信发消息给kc"],
    ["查询明天去闸北公园的路线", "查询明天闸北公园的天气"],
    ["设置明早八点吃药的提醒", "设置下午去医院找医生的提醒"],
    ["向kc发送明天出来玩的消息", "查询明天的天气"],
]
one_shot_choose_app = [
    [
        {
            "app_name": "WeChat",
            "launch_command": "com.tencent.mm/com.tencent.mm.ui.LauncherUI",
            "user_command": "查询余额",
        },
        {
            "app_name": "WeChat",
            "launch_command": "com.tencent.mm/com.tencent.mm.ui.LauncherUI",
            "user_command": "转账给kc",
        },
    ],
    [
        {
            "app_name": "Message",
            "launch_command": "com.android.mms/.ui.ConversationList",
            "user_command": "给小王发消息",
        },
        {
            "app_name": "Message",
            "launch_command": "com.android.mms/.ui.ConversationList",
            "user_command": "给小张发消息",
        },
    ],
    [
        {
            "app_name": "Weather",
            "launch_command": "com.huawei.android.totemweather/.WeatherMainActivity",
            "user_command": "查询今天的天气",
        },
        {
            "app_name": "Feizhu",
            "launch_command": "com.taobao.trip/.home.HomeActivity",
            "user_command": "订购明天去上海的机票",
        },
    ],
    [
        {
            "app_name": "calendar",
            "launch_command": "com.android.calendar/.AllInOneActivity",
            "user_command": "下周一下午三点提醒我去医院拿药",
        },
        {
            "app_name": "calendar",
            "launch_command": "com.android.calendar/.AllInOneActivity",
            "user_command": "下周一下午四点半提醒我去孙子学校接他放学",
        },
    ],
    [
        {
            "app_name": "calendar",
            "launch_command": "com.android.calendar/.AllInOneActivity",
            "user_command": "设置明天会议的提醒",
        },
        {
            "app_name": "WeChat",
            "launch_command": "com.tencent.mm/com.tencent.mm.ui.LauncherUI",
            "user_command": "发消息给kc",
        },
    ],
    [
        {
            "app_name": "baidu map",
            "launch_command": "com.baidu.maps.caring/com.baidu.baidumaps.MapsActivity",
            "user_command": "查询明天去闸北公园的路线",
        },
        {
            "app_name": "Weather",
            "launch_command": "com.huawei.android.totemweather/.WeatherMainActivity",
            "user_command": "查询明天闸北公园的天气",
        },
    ],
    [
        {
            "app_name": "Clock",
            "launch_command": "com.android.deskclock/.AlarmsMainActivity",
            "user_command": "设置明早八点吃药的提醒",
        },
        {
            "app_name": "calendar",
            "launch_command": "com.android.calendar/.AllInOneActivity",
            "user_command": "设置下午去医院找医生的提醒",
        },
    ],
    [
        {
            "app_name": "WeChat",
            "launch_command": "com.tencent.mm/com.tencent.mm.ui.LauncherUI",
            "user_command": "向kc发送明天出来玩的消息",
        },
        {
            "app_name": "Weather",
            "launch_command": "com.huawei.android.totemweather/.WeatherMainActivity",
            "user_command": "查询明天的天气",
        },
    ],
]
