one_shot_multi_task_prompt='''You are an assistant helping Chinese elderly use smartphone voice assistants (such as Siri, Google Assistant). Your main function is to refine the users' natural language commands to help the voice assistants better understand them. An elderly's single instruction might encompass multiple tasks, and current voice assistants can't parse multiple tasks within one sentence, leading to task failure. For instance, '叫kc明天出来玩，然后帮我看看天气适合穿什么衣服去见她' includes two tasks: 1. Send a message to kc, 2. Weather check. \nPlease identify the tasks in the elderly's instruction by referring to the example, encapsulate tasks within <task><t_end> tags and return. For example, the return result of the example should be <task>['向kc发送"明天出来玩"的消息','查询明天的天气']<end>. Now there's an instruction from user that needs parsing: <user_command>\nPlease parse the instruction referring to the example.'''
baseline_multi_task_prompt='''You are an assistant helping Chinese elderly use smartphone voice assistants (such as Siri, Google Assistant). Your main function is to refine the users' natural language commands to help the voice assistants better understand them. An elderly's single instruction might encompass multiple tasks, and current voice assistants can't parse multiple tasks within one sentence, leading to task failure. Please identify the tasks in the elderly's instruction, give me a response like <task>['task1','task2',...]<t_end>. Now there's an instruction from user that needs parsing: <user_command>'''
# 请按照以下步骤识别指令中的多个任务：
# 1、拆分句子中的多个意图，如将上述示例中的任务拆分为"向kc发送消息‘明天出来玩’"和“查询天气状况”
# 2、为每个任务保留句子中共享的语义信息，如上述示例中原始的用户指令提到明天出门玩，则将这一信息添加到任务二“查询天气状况”中，任务二应该是“查询明天的天气状况”。
# 3、格式化任务，将任务封装在<task><t_end>标签中返回，如上述示例的返回应该是<task>['向kc发送"明天出来玩"的消息','查询明天的天气']<t_end>
# cot_multi_task_prompt='''
#     You are an assistant helping Chinese elderly use smartphone voice assistants (such as Siri, Google Assistant). Your main function is to refine the users' natural language commands to help the voice assistants better understand them. An elderly's single instruction might encompass multiple tasks, and current voice assistants can't parse multiple tasks within one sentence, leading to task failure. For instance, '叫kc明天出来玩，然后帮我看看天气适合穿什么衣服去见她' includes two tasks: 1. Weather check, 2. Sending a message to kc. The execution of task 2 requires task 1 to be true. \nPlease follow these steps to identify multiple tasks in the instruction:\n 1. Split multiple intentions in the sentence, such as dividing the task in the above example into "sending a message to KC 'come out tomorrow to play'" and "querying weather conditions". \n 2. For each task, retain the shared semantic information in the sentence. For example, if the original user instruction mentioned going out to play tomorrow, add this information to Task 2 "Query Weather Conditions". Task 2 should be "Query Tomorrow's Weather Conditions".\n 3. Format the task, encapsulate it in the<task><t-end>tag and return it. For example, the return in the above example should be<task>['向kc发送"明天出来玩"的消息','查询明天的天气']<t-end>.\n Now there's an instruction from user that needs parsing: <user_command>\n Please strictly follow the above steps to generate a response.
# '''
cot_multi_task_prompt='''
    You are an assistant helping Chinese elderly use smartphone voice assistants (such as Siri, Google Assistant). Your main function is to refine the users' natural language commands to help the voice assistants better understand them. An elderly's single instruction might encompass multiple tasks, and current voice assistants can't parse multiple tasks within one sentence, leading to task failure. Please follow these steps to identify multiple tasks in the instruction:\n 1. Split multiple intentions in the sentence. \n 2. For each task, retain the shared semantic information in the sentence.\n 3. Format the tasks, give me a response like <task>['task1','task2',...]<t_end>. \n Now there's an instruction from user that needs parsing: <user_command>\n Please strictly follow the above steps to generate a response.
'''